// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efvthmmyvanfxaxzerzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmdnRobW15dmFuZnhheHplcnpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0Mjc2MjEsImV4cCI6MjA3MTAwMzYyMX0.sffyA_hLGNSqiTqXEvz7ytosW4BrLLWIY6eAND5W120";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'X-Client-Info': 'myfuze-app'
    }
  }
});

// Test connection on initialization
if (typeof window !== 'undefined') {
  supabase.auth.getSession().then(({ data, error }) => {
    if (error) {
      console.warn('⚠️ Supabase connection issue:', error.message);
    } else {
      console.log('✅ Supabase connected successfully');
    }
  }).catch((error) => {
    console.error('❌ Failed to connect to Supabase:', error);
  });
}
